apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moshi-moshi
  labels:
    run: moshi-moshi
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: moshi-moshi
    spec:
      containers:
      - name: moshi-moshi
        image: asia.gcr.io/moshi-moshi-3373/moshi-moshi:latest
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
